### ISSUE TITLE
Files not referenced in SourceGraph triggering change events causes problem 

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/imocha#20]
```
(node:7029) UnhandledPromiseRejectionWarning: Error: Change event on unknown file "/home/gno/Projects/imocha/coverage/prettify.js".
    at MochaWatch.fileChanged (/home/gno/Projects/imocha/lib/MochaWatch.js:88:13)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (/home/gno/Projects/imocha/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/home/gno/Projects/imocha/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/home/gno/Projects/imocha/node_modules/chokidar/lib/nodefs-handler.js:267:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by alexjeffburke** [comment]
@gustavnikolaj do you have known a reproduction case for this? :)

**Comment by gustavnikolaj** [comment]
Running coverage after starting imocha in itself should do the trick :-)

ons. 29. aug. 2018 kl. 22.06 skrev Alex J Burke <notifications@github.com>:

**Comment by alexjeffburke** [comment]
Hmmm, just tried but I can't seem to replicate this.
